[package]
name = "humanerr"
version = "0.1.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvfmt = { path = "/home/jlusby/git/rust/kvfmt" }
anyhow = "1.0.25"
